spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#    aplication.properties kar??l???
#

# Veritaban? ba?lant? ayarlar?
#    spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_security
#    spring.datasource.username=postgres
#    spring.datasource.password=12345
#    spring.datasource.driver-class-name=org.postgresql.Driver
#
#    # JPA ve Hibernate ayarlar?
#    spring.jpa.hibernate.ddl-auto=create-drop
#    spring.jpa.show-sql=true
#    spring.jpa.properties.hibernate.format_sql=true
#
#    spring.jpa.database=postgresql
#    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
